/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author Brayan Guillen N
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNaciones = new javax.swing.JButton();
        btnEstReg = new javax.swing.JButton();
        btnDepartamentos = new javax.swing.JButton();
        btnColores = new javax.swing.JButton();
        btnClaseCigarro = new javax.swing.JButton();
        btnProvincias = new javax.swing.JButton();
        btnDistritos = new javax.swing.JButton();
        btnDistritos1 = new javax.swing.JButton();
        btnEstancos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnFabricantes1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnNaciones.setText("Naciones");
        btnNaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNacionesActionPerformed(evt);
            }
        });

        btnEstReg.setText("Estado Registro");
        btnEstReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstRegActionPerformed(evt);
            }
        });

        btnDepartamentos.setText("Departamentos");
        btnDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepartamentosActionPerformed(evt);
            }
        });

        btnColores.setText("Colores");
        btnColores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColoresActionPerformed(evt);
            }
        });

        btnClaseCigarro.setText("Clase Cigarro");
        btnClaseCigarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClaseCigarroActionPerformed(evt);
            }
        });

        btnProvincias.setText("Provincias");
        btnProvincias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProvinciasActionPerformed(evt);
            }
        });

        btnDistritos.setText("Distritos");
        btnDistritos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDistritosActionPerformed(evt);
            }
        });

        btnDistritos1.setText("Cigarrillos");
        btnDistritos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDistritos1ActionPerformed(evt);
            }
        });

        btnEstancos.setText("Estancos");
        btnEstancos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstancosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setText("MAESTROS HUB");

        btnFabricantes1.setText("Fabricantes");
        btnFabricantes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFabricantes1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEstancos)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnNaciones)
                                    .addComponent(btnColores)
                                    .addComponent(btnDistritos))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEstReg)
                                    .addComponent(btnClaseCigarro)
                                    .addComponent(btnDistritos1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDepartamentos)
                                    .addComponent(btnProvincias))))
                        .addGap(0, 24, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(265, Short.MAX_VALUE)
                    .addComponent(btnFabricantes1)
                    .addGap(42, 42, 42)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNaciones)
                    .addComponent(btnEstReg)
                    .addComponent(btnDepartamentos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnColores)
                    .addComponent(btnClaseCigarro)
                    .addComponent(btnProvincias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDistritos)
                    .addComponent(btnDistritos1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEstancos)
                .addContainerGap(119, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(194, Short.MAX_VALUE)
                    .addComponent(btnFabricantes1)
                    .addGap(143, 143, 143)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNacionesActionPerformed
        new MNacionesView().setVisible(true);
    }//GEN-LAST:event_btnNacionesActionPerformed

    private void btnEstRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstRegActionPerformed
        new MEstadoRegistroView().setVisible(true);
    }//GEN-LAST:event_btnEstRegActionPerformed

    private void btnDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepartamentosActionPerformed
        new MDepartamentosView().setVisible(true);
    }//GEN-LAST:event_btnDepartamentosActionPerformed

    private void btnColoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColoresActionPerformed
        new MColoresView().setVisible(true);
    }//GEN-LAST:event_btnColoresActionPerformed

    private void btnClaseCigarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClaseCigarroActionPerformed
        new MClaseCigarroView().setVisible(true);
    }//GEN-LAST:event_btnClaseCigarroActionPerformed

    private void btnProvinciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProvinciasActionPerformed
        new MProvinciasView().setVisible(true);
    }//GEN-LAST:event_btnProvinciasActionPerformed

    private void btnDistritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDistritosActionPerformed
        new MDistritosView().setVisible(true);
    }//GEN-LAST:event_btnDistritosActionPerformed

    private void btnDistritos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDistritos1ActionPerformed
        new MCigarrillosView().setVisible(true);
    }//GEN-LAST:event_btnDistritos1ActionPerformed

    private void btnEstancosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstancosActionPerformed
        new MEstancosView().setVisible(true);
    }//GEN-LAST:event_btnEstancosActionPerformed

    private void btnFabricantes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFabricantes1ActionPerformed
        new MFabricantesView().setVisible(true);
    }//GEN-LAST:event_btnFabricantes1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClaseCigarro;
    private javax.swing.JButton btnColores;
    private javax.swing.JButton btnDepartamentos;
    private javax.swing.JButton btnDistritos;
    private javax.swing.JButton btnDistritos1;
    private javax.swing.JButton btnEstReg;
    private javax.swing.JButton btnEstancos;
    private javax.swing.JButton btnFabricantes1;
    private javax.swing.JButton btnNaciones;
    private javax.swing.JButton btnProvincias;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
