/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.EstadoRegistro;
import modelos.Cigarrillo;
import modelos.ColorM;
import modelos.ClaseCigarro;
import modelos.ControllerResponse;
import controladores.EstadoRegistrosController;
import controladores.CigarrillosController;
import controladores.ColoresController;
import controladores.ClaseCigarrosController;
import config.Connector;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;


/**
 *
 * @author Brayan Guillen N
 */
public class MCigarrillosView extends javax.swing.JFrame {
    
    private ArrayList<ColorM> colores;
    private ArrayList<ClaseCigarro> clasesCigarros;
    private int estado = 0;
    /*
    Maneja elestado del formulario
    0 = Ninguna accion
    1 = Adicionando
    2 = Modificando
    3 = Eliminando
    4 = Inactivando
    5 = Reactivando
    */
    private EstadoRegistrosController estRegController;
    private CigarrillosController cigarrillosController;
    private ColoresController coloresController;
    private ClaseCigarrosController claCigController;
    private Connector db;
    /**
     * Creates new form MNacionesView
     */
    public MCigarrillosView() {
        this.db = new Connector();
        estRegController = new EstadoRegistrosController(db.getConnection());
        cigarrillosController = new CigarrillosController(db.getConnection());
        coloresController = new ColoresController(db.getConnection());
        claCigController = new ClaseCigarrosController(db.getConnection());
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        this.txtCodigo.setEnabled(false);
        this.txtMarca.setEnabled(false);
         this.txtAlquitran.setEnabled(false);
        this.txtNicotina.setEnabled(false);
        this.txtCarton.setEnabled(false);
        this.txtEmboltura.setEnabled(false);
        this.txtPrecioCosto.setEnabled(false);
        this.txtPrecioVenta.setEnabled(false);
        this.chkMentol.setEnabled(false);
        this.chkFiltro.setEnabled(false);
        this.cbxClase.setEnabled(false);
        this.cbxColor.setEnabled(false);
        this.txtEstReg.setEnabled(false);
        this.setLocationRelativeTo(null);
        cargarTabla();
        cargarComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        chkMentol = new javax.swing.JCheckBox();
        chkFiltro = new javax.swing.JCheckBox();
        txtCarton = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNicotina = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtAlquitran = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPrecioCosto = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtPrecioVenta = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtEmboltura = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtEstReg = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cbxColor = new javax.swing.JComboBox<>();
        cbxClase = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnAdicionar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnInactivar = new javax.swing.JButton();
        btnReactivar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Maestro de naciones");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(56, 12, 86));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CIGARRILLOS");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gestiona los registros de cigarrillos en el sistema");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del cigarrillos"));

        jLabel3.setText("Codigo:");

        jLabel4.setText("Marca:");

        jLabel9.setText("Carton:");

        chkMentol.setText("Mentol");
        chkMentol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMentolActionPerformed(evt);
            }
        });

        chkFiltro.setText("Filtro");
        chkFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFiltroActionPerformed(evt);
            }
        });

        jLabel10.setText("Nicotina:");

        jLabel11.setText("Alquitran:");

        jLabel12.setText("Precio Costo:");

        jLabel13.setText("Precio Venta:");

        jLabel14.setText("Emboltura:");

        jLabel15.setText("Estado Registro:");

        jLabel16.setText("Color:");

        jLabel17.setText("Clase:");

        cbxColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbxClase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(chkFiltro)
                                .addGap(18, 18, 18)
                                .addComponent(chkMentol))
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAlquitran, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNicotina, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCarton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel14))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEmboltura, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrecioCosto)
                                    .addComponent(txtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxColor, 0, 95, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEstReg, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxClase, 0, 95, Short.MAX_VALUE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5)))
                .addGap(33, 33, 33))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtPrecioCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel13)
                    .addComponent(txtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkMentol)
                    .addComponent(chkFiltro)
                    .addComponent(jLabel14)
                    .addComponent(txtEmboltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtCarton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(cbxColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtNicotina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(cbxClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtAlquitran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtEstReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabla de registros"));

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Marca", "Filtro", "Mentol", "Carton", "Nicotina", "Alquitran", "P. Costo", "P. Venta", "Emboltura", "Estado Registro"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblData.setSelectionForeground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(tblData);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion del estado"));

        jLabel6.setText("Accion:");

        lblEstado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstado.setText("Ninguna");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(79, 79, 79))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEstado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnInactivar.setText("Inactivar");
        btnInactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInactivarActionPerformed(evt);
            }
        });

        btnReactivar.setText("Reactivar");
        btnReactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReactivarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInactivar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnReactivar, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnActualizar)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar)
                    .addComponent(btnActualizar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(btnCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInactivar)
                    .addComponent(btnReactivar)
                    .addComponent(btnSalir))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed

        this.cambiarEstado(1);
        this.txtCodigo.setText("");
        this.txtMarca.setText("");
        this.txtAlquitran.setText("");
        this.txtNicotina.setText("");
        this.txtCarton.setText("");
        this.txtEmboltura.setText("");
        this.txtPrecioCosto.setText("");
        this.txtPrecioVenta.setText("");
        this.chkFiltro.setSelected(false);
        this.chkMentol.setSelected(false);
        this.cbxClase.setSelectedIndex(0);
        this.cbxColor.setSelectedIndex(0);
        EstadoRegistro estReg = estRegController.search(1); //Buscamos el estado de registro con codigo 1
        this.txtEstReg.setText(estReg.getDescripcion());
        this.txtCodigo.setEnabled(true);
        this.txtMarca.setEnabled(true);
        this.txtAlquitran.setEnabled(true);
        this.txtNicotina.setEnabled(true);
        this.txtCarton.setEnabled(true);
        this.txtEmboltura.setEnabled(true);
        this.txtPrecioCosto.setEnabled(true);
        this.txtPrecioVenta.setEnabled(true);
        this.chkMentol.setEnabled(true);
        this.chkFiltro.setEnabled(true);
        this.cbxClase.setEnabled(true);
        this.cbxColor.setEnabled(true);
        this.txtEstReg.setEnabled(false);
        this.txtCodigo.requestFocus();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int indexRow = this.tblData.getSelectedRow();
        if(indexRow == -1){
            JOptionPane.showMessageDialog(this, "Tiene que selecionar un registro de la tabla", "Elegir uno", JOptionPane.ERROR_MESSAGE);
            this.btnCancelar.doClick();
            return;
        }
        this.cambiarEstado(2);
        DefaultTableModel modeloTabla = (DefaultTableModel) this.tblData.getModel();
        Cigarrillo cigarrillo = cigarrillosController.search( (String) modeloTabla.getValueAt(indexRow, 0));
        EstadoRegistro estReg= estRegController.search(cigarrillo.getEstadoRegistro());
        ColorM color = coloresController.search(cigarrillo.getColorCodigo());
        ClaseCigarro claCig = claCigController.search(cigarrillo.getClaseCodigo());
        this.txtCodigo.setText(cigarrillo.getCodigo());
        this.txtMarca.setText(cigarrillo.getMarca());
        this.txtAlquitran.setText(cigarrillo.getAlquitran()+"");
        this.txtNicotina.setText(cigarrillo.getNicotina()+"");
        this.txtCarton.setText(cigarrillo.getCarton()+"");
        this.txtEmboltura.setText(cigarrillo.getEmboltura()+"");
        this.txtPrecioCosto.setText(cigarrillo.getPrecioCompra()+"");
        this.txtPrecioVenta.setText(cigarrillo.getPrecioVenta()+"");
        this.cbxColor.setSelectedItem(color.getNombre());
        this.cbxClase.setSelectedItem(claCig.getNombre());
        this.chkFiltro.setSelected(cigarrillo.getFiltro());
        this.chkMentol.setSelected(cigarrillo.getMentol());
        this.txtEstReg.setText(estReg.getDescripcion());
        this.txtCodigo.setEnabled(false);
        this.txtEstReg.setEnabled(false);
        this.txtMarca.setEnabled(true);
        this.txtAlquitran.setEnabled(true);
        this.txtNicotina.setEnabled(true);
        this.txtCarton.setEnabled(true);
        this.txtEmboltura.setEnabled(true);
        this.txtPrecioCosto.setEnabled(true);
        this.txtPrecioVenta.setEnabled(true);
        this.chkMentol.setEnabled(true);
        this.chkFiltro.setEnabled(true);
        this.cbxClase.setEnabled(true);
        this.cbxColor.setEnabled(true);
        this.txtMarca.requestFocus();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnInactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInactivarActionPerformed
        int indexRow = this.tblData.getSelectedRow();
        if(indexRow == -1){
            JOptionPane.showMessageDialog(this, "Tiene que selecionar un registro de la tabla", "Elegir uno", JOptionPane.ERROR_MESSAGE);
            this.btnCancelar.doClick();
            return;
        }
        this.cambiarEstado(4);
        DefaultTableModel modeloTabla = (DefaultTableModel) this.tblData.getModel();
        Cigarrillo cigarrillo = cigarrillosController.search( (String) modeloTabla.getValueAt(indexRow, 0));
        EstadoRegistro estReg = estRegController.search(3);
        ColorM color = coloresController.search(cigarrillo.getColorCodigo());
        ClaseCigarro claCig = claCigController.search(cigarrillo.getClaseCodigo());
        this.txtCodigo.setText(cigarrillo.getCodigo());
        this.txtMarca.setText(cigarrillo.getMarca());
        this.txtAlquitran.setText(cigarrillo.getAlquitran()+"");
        this.txtNicotina.setText(cigarrillo.getNicotina()+"");
        this.txtCarton.setText(cigarrillo.getCarton()+"");
        this.txtEmboltura.setText(cigarrillo.getEmboltura()+"");
        this.txtPrecioCosto.setText(cigarrillo.getPrecioCompra()+"");
        this.txtPrecioVenta.setText(cigarrillo.getPrecioVenta()+"");
        this.cbxColor.setSelectedItem(color.getNombre());
        this.cbxClase.setSelectedItem(claCig.getNombre());
        this.chkFiltro.setSelected(cigarrillo.getFiltro());
        this.chkMentol.setSelected(cigarrillo.getMentol());
        this.txtEstReg.setText(estReg.getDescripcion());
        this.txtCodigo.setEnabled(false);
        this.txtMarca.setEnabled(false);
        this.txtAlquitran.setEnabled(false);
        this.txtNicotina.setEnabled(false);
        this.txtCarton.setEnabled(false);
        this.txtEmboltura.setEnabled(false);
        this.txtPrecioCosto.setEnabled(false);
        this.txtPrecioVenta.setEnabled(false);
        this.chkMentol.setEnabled(false);
        this.chkFiltro.setEnabled(false);
        this.cbxClase.setEnabled(false);
        this.cbxColor.setEnabled(false);
        this.txtEstReg.setEnabled(false);
    }//GEN-LAST:event_btnInactivarActionPerformed

    private void btnReactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReactivarActionPerformed
        int indexRow = this.tblData.getSelectedRow();
        if(indexRow == -1){
            JOptionPane.showMessageDialog(this, "Tiene que selecionar un registro de la tabla", "Elegir uno", JOptionPane.ERROR_MESSAGE);
            this.btnCancelar.doClick();
            return;
        }
        this.cambiarEstado(5);
        DefaultTableModel modeloTabla = (DefaultTableModel) this.tblData.getModel();
        Cigarrillo cigarrillo = cigarrillosController.search( (String) modeloTabla.getValueAt(indexRow, 0));
        EstadoRegistro estReg = estRegController.search(1);
        ColorM color = coloresController.search(cigarrillo.getColorCodigo());
        ClaseCigarro claCig = claCigController.search(cigarrillo.getClaseCodigo());
        this.txtCodigo.setText(cigarrillo.getCodigo());
        this.txtMarca.setText(cigarrillo.getMarca());
        this.txtAlquitran.setText(cigarrillo.getAlquitran()+"");
        this.txtNicotina.setText(cigarrillo.getNicotina()+"");
        this.txtCarton.setText(cigarrillo.getCarton()+"");
        this.txtEmboltura.setText(cigarrillo.getEmboltura()+"");
        this.txtPrecioCosto.setText(cigarrillo.getPrecioCompra()+"");
        this.txtPrecioVenta.setText(cigarrillo.getPrecioVenta()+"");
        this.cbxColor.setSelectedItem(color.getNombre());
        this.cbxClase.setSelectedItem(claCig.getNombre());
        this.chkFiltro.setSelected(cigarrillo.getFiltro());
        this.chkMentol.setSelected(cigarrillo.getMentol());
        this.txtEstReg.setText(estReg.getDescripcion());
        this.txtCodigo.setEnabled(false);
        this.txtMarca.setEnabled(false);
        this.txtAlquitran.setEnabled(false);
        this.txtNicotina.setEnabled(false);
        this.txtCarton.setEnabled(false);
        this.txtEmboltura.setEnabled(false);
        this.txtPrecioCosto.setEnabled(false);
        this.txtPrecioVenta.setEnabled(false);
        this.chkMentol.setEnabled(false);
        this.chkFiltro.setEnabled(false);
        this.cbxClase.setEnabled(false);
        this.cbxColor.setEnabled(false);
        this.txtEstReg.setEnabled(false);
    }//GEN-LAST:event_btnReactivarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        if(estado != 0){
            int resp = JOptionPane.showConfirmDialog(this, "Estas realizando una acción ¿Realmente deseas salir?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if(resp == 0) this.dispose();
        }else{
            this.dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int indexRow = this.tblData.getSelectedRow();
        if(indexRow == -1){
            JOptionPane.showMessageDialog(this, "Tiene que selecionar un registro de la tabla", "Elegir uno", JOptionPane.ERROR_MESSAGE);
            this.btnCancelar.doClick();
            return;
        }
        this.cambiarEstado(3);
        DefaultTableModel modeloTabla = (DefaultTableModel) this.tblData.getModel();
        Cigarrillo cigarrillo = cigarrillosController.search( (String) modeloTabla.getValueAt(indexRow, 0));
        EstadoRegistro estReg = estRegController.search(2);
        ColorM color = coloresController.search(cigarrillo.getColorCodigo());
        ClaseCigarro claCig = claCigController.search(cigarrillo.getClaseCodigo());
        this.txtCodigo.setText(cigarrillo.getCodigo());
        this.txtMarca.setText(cigarrillo.getMarca());
        this.txtAlquitran.setText(cigarrillo.getAlquitran()+"");
        this.txtNicotina.setText(cigarrillo.getNicotina()+"");
        this.txtCarton.setText(cigarrillo.getCarton()+"");
        this.txtEmboltura.setText(cigarrillo.getEmboltura()+"");
        this.txtPrecioCosto.setText(cigarrillo.getPrecioCompra()+"");
        this.txtPrecioVenta.setText(cigarrillo.getPrecioVenta()+"");
        this.cbxColor.setSelectedItem(color.getNombre());
        this.cbxClase.setSelectedItem(claCig.getNombre());
        this.chkFiltro.setSelected(cigarrillo.getFiltro());
        this.chkMentol.setSelected(cigarrillo.getMentol());
        this.txtEstReg.setText(estReg.getDescripcion());
        this.txtCodigo.setEnabled(false);
        this.txtMarca.setEnabled(false);
        this.txtAlquitran.setEnabled(false);
        this.txtNicotina.setEnabled(false);
        this.txtCarton.setEnabled(false);
        this.txtEmboltura.setEnabled(false);
        this.txtPrecioCosto.setEnabled(false);
        this.txtPrecioVenta.setEnabled(false);
        this.chkMentol.setEnabled(false);
        this.chkFiltro.setEnabled(false);
        this.cbxClase.setEnabled(false);
        this.cbxColor.setEnabled(false);
        this.txtEstReg.setEnabled(false);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.cambiarEstado(0);
        this.txtCodigo.setText("");
        this.txtMarca.setText("");
        this.txtAlquitran.setText("");
        this.txtNicotina.setText("");
        this.txtCarton.setText("");
        this.txtEmboltura.setText("");
        this.txtPrecioCosto.setText("");
        this.txtPrecioVenta.setText("");
        this.txtEstReg.setText("");
        this.chkFiltro.setSelected(false);
        this.chkMentol.setSelected(false);
        this.cbxClase.setSelectedIndex(0);
        this.cbxColor.setSelectedIndex(0);
        this.txtCodigo.setEnabled(false);
        this.txtMarca.setEnabled(false);
         this.txtAlquitran.setEnabled(false);
        this.txtNicotina.setEnabled(false);
        this.txtCarton.setEnabled(false);
        this.txtEmboltura.setEnabled(false);
        this.txtPrecioCosto.setEnabled(false);
        this.txtPrecioVenta.setEnabled(false);
        this.chkMentol.setEnabled(false);
        this.chkFiltro.setEnabled(false);
        this.cbxClase.setEnabled(false);
        this.cbxColor.setEnabled(false);
        this.txtEstReg.setEnabled(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        switch(estado){
            case 0:
                JOptionPane.showMessageDialog(this, "Ninguna accion se esta realizando", "Informacion", JOptionPane.WARNING_MESSAGE);
                break;
            case 1:
                adicionarNuevo();
                break;
            case 2:
                modificarRegistro();
                break;
            case 3:
                eliminarRegistro();
                break;
            case 4:
                inactivarRegistro();
                break;
            case 5:
                reactivarRegistro();
                break;
            default:
                JOptionPane.showMessageDialog(this, "Error accion no reconocida", "Error en la accion", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void chkMentolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMentolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkMentolActionPerformed

    private void chkFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkFiltroActionPerformed

    private void cargarComboBox(){
        colores = coloresController.getAll();
        this.cbxColor.removeAllItems();
        for(int i=0; i<colores.size();i++)
            if(colores.get(i).getEstadoRegistro() != 2)
                this.cbxColor.addItem(colores.get(i).getNombre());
        this.cbxColor.setSelectedIndex(0);
        
        clasesCigarros = claCigController.getAll();
        this.cbxClase.removeAllItems();
        for(int i=0; i<clasesCigarros.size();i++)
            if(clasesCigarros.get(i).getEstadoRegistro() != 2)
                this.cbxClase.addItem(clasesCigarros.get(i).getNombre());
        this.cbxClase.setSelectedIndex(0);
    }
    
    private void cambiarEstado(int estado){
        this.estado = estado;
        String text = "";
        switch(estado){
            case 0: text = "Ninguna"; break;
            case 1: text = "Adicionando"; break;
            case 2: text = "Modificando"; break;
            case 3: text = "Eliminando"; break;
            case 4: text = "Inactivando"; break;
            case 5: text = "Reactivando"; break;
        }
        lblEstado.setText(text);
    }

    private void cargarTabla(){
        DefaultTableModel modeloTabla = new DefaultTableModel();
        ArrayList<Cigarrillo> data = cigarrillosController.getAll();
        modeloTabla.setColumnIdentifiers(new Object[]{"Codigo", "Marca","Filtro" ,"Color", "Clase", "Mentol", "Carton", "Nicotina", "Alquitran", "P. Compra", "P. Venta", "Emboltura", "Estado Registro"});
        EstadoRegistro estReg;
        ColorM color;
        ClaseCigarro claseCig;
        try{
             for(int i=0; i < data.size(); i++){
                 estReg = estRegController.search(data.get(i).getEstadoRegistro());
                 color = coloresController.search(data.get(i).getColorCodigo());
                 claseCig = claCigController.search(data.get(i).getClaseCodigo());
                 if(estReg.getCodigo() != 2){
                     modeloTabla.addRow(new Object[]{
                        data.get(i).getCodigo(),
                        data.get(i).getMarca(),
                        data.get(i).getFiltro(),
                        color.getNombre(),
                        claseCig.getNombre(),
                        data.get(i).getMentol(),
                        data.get(i).getCarton(),
                        data.get(i).getNicotina(),
                        data.get(i).getAlquitran(),
                        data.get(i).getPrecioCompra(),
                        data.get(i).getPrecioVenta(),
                        data.get(i).getEmboltura(),
                        estReg.getDescripcion()
                     });
                 }
             }
             this.tblData.setModel(modeloTabla);
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrio un error durante la carga de datos", "Error inesperado", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }
    
    private void adicionarNuevo(){
        String ventanaTitle = "Informacion de adiccionar";
        if(txtCodigo.getText().isBlank() || txtMarca.getText().isBlank() || txtCarton.getText().isBlank() || txtNicotina.getText().isBlank() || txtAlquitran.getText().isBlank() || txtPrecioCosto.getText().isBlank() || txtPrecioVenta.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "Debe completar todos los campos", ventanaTitle, JOptionPane.ERROR_MESSAGE);
            return;
        }
        int codigo,carton,emboltura;
        float alq, nic, pcom, pven;
        try{
            codigo = Integer.parseInt(this.txtCodigo.getText());
            carton = Integer.parseInt(this.txtCarton.getText());
            emboltura = Integer.parseInt(this.txtEmboltura.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "El campo codigo debe ser un numero entero", ventanaTitle,JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try{
            alq = Float.parseFloat(this.txtAlquitran.getText());
            nic = Float.parseFloat(this.txtNicotina.getText());
            pcom = Float.parseFloat(this.txtPrecioCosto.getText());
            pven = Float.parseFloat(this.txtPrecioVenta.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Los campos nicotina, alquitran, precio compra, precio venta deben ser float", ventanaTitle,JOptionPane.ERROR_MESSAGE);
            return;
        }
        int indexCol = this.cbxColor.getSelectedIndex();
        int indexCla = this.cbxClase.getSelectedIndex();
        Cigarrillo cigarrillo = new Cigarrillo(
                codigo+"",
                this.txtMarca.getText(),
                this.chkFiltro.isSelected(),
                this.colores.get(indexCol).getCodigo(),
                this.clasesCigarros.get(indexCla).getCodigo(),
                this.chkMentol.isSelected(),
                carton,
                nic,
                alq,
                pven,
                pcom,
                emboltura,
                1
        );
        ControllerResponse resp = cigarrillosController.adiccionar(cigarrillo);
        if(resp.isOk()){
            JOptionPane.showMessageDialog(this, resp.getMessage(), ventanaTitle, JOptionPane.INFORMATION_MESSAGE);
            cargarTabla();
            btnCancelar.doClick();
        }else{
            JOptionPane.showMessageDialog(this, resp.getMessage(), ventanaTitle, JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void modificarRegistro(){
        String ventanaTitle = "Información de la modificacion";
        if(this.txtMarca.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "El valor del nombre y la descripcion no puede ser vacio", ventanaTitle, JOptionPane.ERROR_MESSAGE);
            return;
        }
        int carton,emboltura;
        float alq, nic, pcom, pven;
        try{
            carton = Integer.parseInt(this.txtCarton.getText());
            emboltura = Integer.parseInt(this.txtEmboltura.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "El campo codigo debe ser un numero entero", ventanaTitle,JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try{
            alq = Float.parseFloat(this.txtAlquitran.getText());
            nic = Float.parseFloat(this.txtNicotina.getText());
            pcom = Float.parseFloat(this.txtPrecioCosto.getText());
            pven = Float.parseFloat(this.txtPrecioVenta.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Los campos nicotina, alquitran, precio compra, precio venta deben ser float", ventanaTitle,JOptionPane.ERROR_MESSAGE);
            return;
        }
        int opc = JOptionPane.showConfirmDialog(this, "¿Realmente deseas realizar los cambios?", ventanaTitle, JOptionPane.YES_NO_OPTION);
        if(opc == JOptionPane.YES_OPTION){
            Cigarrillo cigarrillo = cigarrillosController.search(this.txtCodigo.getText());
            if(cigarrillo != null){
                int indexCol = this.cbxColor.getSelectedIndex();
                int indexCla = this.cbxClase.getSelectedIndex();
                cigarrillo.setMarca(this.txtMarca.getText());
                cigarrillo.setFiltro(this.chkFiltro.isSelected());
                cigarrillo.setColorCodigo(this.colores.get(indexCol).getCodigo());
                cigarrillo.setClaseCodigo(this.clasesCigarros.get(indexCla).getCodigo());
                cigarrillo.setMentol(this.chkMentol.isSelected());
                cigarrillo.setCarton(carton);
                cigarrillo.setNicotina(nic);
                cigarrillo.setAlquitran(alq);
                cigarrillo.setPrecioCompra(pcom);
                cigarrillo.setPrecioVenta(pven);
                cigarrillo.setEmboltura(emboltura);
                ControllerResponse resp = cigarrillosController.modificar(cigarrillo);
                if(resp.isOk()){
                    JOptionPane.showMessageDialog(this, resp.getMessage(), ventanaTitle, JOptionPane.INFORMATION_MESSAGE);
                    cargarTabla();
                }else{
                    JOptionPane.showMessageDialog(this, resp.getMessage(), ventanaTitle, JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(this, "No se encontro el registro", ventanaTitle, JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Accion cancelada con exito", ventanaTitle, JOptionPane.INFORMATION_MESSAGE);
        }
        btnCancelar.doClick();
    }
    
    private void eliminarRegistro(){
        String ventanaTitle = "Información de la eliminación";
        int opc = JOptionPane.showConfirmDialog(this, "¿Realmente desea eliminar el registro?", ventanaTitle, JOptionPane.YES_NO_OPTION);
        if(opc == JOptionPane.YES_OPTION){
            ControllerResponse resp = cigarrillosController.eliminar(this.txtCodigo.getText());
            if(resp.isOk()){
                JOptionPane.showMessageDialog(this, resp.getMessage(), ventanaTitle, JOptionPane.INFORMATION_MESSAGE);
                cargarTabla();
            }else{
                JOptionPane.showMessageDialog(this, resp.getMessage(), ventanaTitle, JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Operacion cancelada con exito", ventanaTitle, JOptionPane.INFORMATION_MESSAGE);
        }
        btnCancelar.doClick();
    }
    
    private void inactivarRegistro(){
        String ventanaTitle = "Información de la inactivación";
        int opc = JOptionPane.showConfirmDialog(this, "¿Realmente desea inactivar el registro?", ventanaTitle, JOptionPane.YES_NO_OPTION);
        if(opc == JOptionPane.YES_OPTION){
            ControllerResponse resp = cigarrillosController.inactivar(this.txtCodigo.getText());
            if(resp.isOk()){
                JOptionPane.showMessageDialog(this, resp.getMessage(), ventanaTitle, JOptionPane.INFORMATION_MESSAGE);
                cargarTabla();
            }else{
                JOptionPane.showMessageDialog(this, resp.getMessage(), ventanaTitle, JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Operacion cancelada con exito", ventanaTitle, JOptionPane.INFORMATION_MESSAGE);
        }
        btnCancelar.doClick();
    }
    
    private void reactivarRegistro(){
        String ventanaTitle = "Información de la reactivación";
        int opc = JOptionPane.showConfirmDialog(this, "¿Realmente desea reactivar el registro?", ventanaTitle, JOptionPane.YES_NO_OPTION);
        if(opc == JOptionPane.YES_OPTION){
            ControllerResponse resp = cigarrillosController.reactivar(this.txtCodigo.getText());
            if(resp.isOk()){
                JOptionPane.showMessageDialog(this, resp.getMessage(), ventanaTitle, JOptionPane.INFORMATION_MESSAGE);
                cargarTabla();
            }else{
                JOptionPane.showMessageDialog(this, resp.getMessage(), ventanaTitle, JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Operacion cancelada con exito", ventanaTitle, JOptionPane.INFORMATION_MESSAGE);
        }
        btnCancelar.doClick();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MCigarrillosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MCigarrillosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MCigarrillosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MCigarrillosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MCigarrillosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInactivar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnReactivar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbxClase;
    private javax.swing.JComboBox<String> cbxColor;
    private javax.swing.JCheckBox chkFiltro;
    private javax.swing.JCheckBox chkMentol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JTable tblData;
    private javax.swing.JTextField txtAlquitran;
    private javax.swing.JTextField txtCarton;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtEmboltura;
    private javax.swing.JTextField txtEstReg;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNicotina;
    private javax.swing.JTextField txtPrecioCosto;
    private javax.swing.JTextField txtPrecioVenta;
    // End of variables declaration//GEN-END:variables
}
